name: CI
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  get-python-version:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get python version
        id: get-version
        run: |
          # Read the file, trim whitespace/newlines, and set as output
          echo "version=$(cat .python-version | xargs)" >> $GITHUB_OUTPUT

  ruff-lint-and-format:
    needs: get-python-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python with Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ needs.get-python-version.outputs.python-version }}

      - name: Run tests
        run: poetry run pre-commit run --all-files

  pytest:
    runs-on: ubuntu-latest
    needs: [get-python-version, ruff-lint-and-format]
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python with Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ needs.get-python-version.outputs.python-version }}

      - name: Run tests
        run: poetry run pytest -v --durations=0 --cov --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}